# Generated by Django 5.2.4 on 2025-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbooking', '0002_booking_route_delete_busroute_booking_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='travel_date',
            field=models.DateField(default='2025-08-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
