# Generated by Django 5.2.4 on 2025-08-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbooking', '0003_route_travel_date_alter_booking_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
